# Generated by Django 5.2 on 2026-07-08 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KodeSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jenis', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NoSuratFakultas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('tahun', models.CharField(max_length=5)),
                ('nomor', models.IntegerField()),
                ('perihal', models.CharField(max_length=255)),
                ('tujuan', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=50)),
                ('adminp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nosuratf_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdminFakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
